kind: Deployment
apiVersion: apps/v1
metadata:
  name: addressbook
  labels:
    app: firstweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: firstweb
  template:
    metadata:
      labels:
        app: firstweb
    spec:
      containers:
      - name: firstweb
        image: adarshadhal/firstweb:latest
        ports:
        - name: http
          containerPort: 8082

---
kind: Service
apiVersion: v1
metadata:
  name: addressbook-svc
spec:
  type: NodePort
  selector:
    app: firstweb
  ports:
  - port: 80
    targetPort: 8082
    nodePort: 30001
