apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstweb-dpl
  labels:
    app: firstweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: firstweb
  template:
    metadata:
      labels:
        app: firstweb
    spec:
      containers:
      - name: firstweb
        image: adarshadhal/firstweb:22
        ports:
        - name: http
          containerPort: 8082
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: firstweb-svc
spec:
  type: NodePort
  selector:
    app: firstweb
  ports:
  - port: 80          # Service port (standard HTTP)
    targetPort: 8080    # Your Tomcat container port
    nodePort: 30001     # External access port
    protocol: TCP
    name: http
